WRMCB=function(e){var c=console;if(c&&c.log&&c.error){c.log('Error running batched script.');c.error(e);}}
;
try {
/* module-key = 'com.atlassian.plugins.atlassian-connect-plugin:iframe-insertion-v5', location = 'v5/js/iframe/combined/iframe-insertion.js' */
(function(){function h(a){var c;if("string"===typeof a&&1<a.length)try{c=JSON.parse(a)}catch(b){console.error("ACJS: failed to decode context",a)}"object"!==typeof c&&(c={});return c}function l(a,c){if("number"!==typeof a)return window.top;c=c||window;for(var b=0;b<a;b++)c=c.parent;return c}function g(a){function c(){var a=document.getElementById(b.containerId);window._AP.addonAttemptCounter[b.containerId]++;if(a)if(delete window._AP.addonAttemptCounter[b.containerId],window._AP.isSubHost){a.appendChild(d);
var a=d.contentDocument,f="(function(){ var w \x3d window; for (var i\x3d0; i\x3c"+b.options.hostFrameOffset+"; i++){w \x3d w.parent; } w.postMessage("+JSON.stringify({type:"set_inner_iframe_url",iframeData:b})+', "*");}());';a.open();a.write("\x3cscript\x3e"+f+"\x3c/script\x3e");a.close()}else{if(f=a.querySelector(".ap-iframe-container"))f.parentNode.removeChild(f),AJS.log&&AJS.log("AJS: duplicate iframe removed",b,a);d.appendTo(a);d.data("addon-key",b.addon_key);d.data("key",b.key)}else 10>=window._AP.addonAttemptCounter[b.containerId]&&
m(c)}window._AP.isSubHost=l(a.hostFrameOffset)!==window;var b=window._AP._convertConnectOptions(a),d;window._AP.isSubHost?(window.AP&&window.AP._data&&window.AP._data.options&&window.AP._data.options.globalOptions&&(b.options.globalOptions=window.AP._data.options.globalOptions),d=window._AP._createSub(b)):(n({addon_key:b.addon_key,key:b.key}).forEach(function(a){if(a.extension.options.uniqueKey===b.options.uniqueKey){var c=document.getElementById(a.extension_id);e().destroy(a.extension_id);c&&AJS.$(c).closest(".ap-iframe-container").remove()}},
this),d=e().create(b));window._AP.addonAttemptCounter[b.containerId]=0;c()}var m=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||function(a){window.setTimeout(a,50)}}(),e=function(){return window.connectHost||window.AP},n=function(a){return e().getExtensions(a).filter(function(a){return!!document.getElementById(a.extension_id)})},k=function(a,c,b){try{var d=require(a);c(d)}catch(p){0>=b?(console.error("Unable to load module: "+a),
c(null)):setTimeout(function(){k(a,c,b-1)},500)}};window._AP=window._AP||{};window._AP.addonAttemptCounter=window._AP.addonAttemptCounter||{};window._AP._convertConnectOptions=function(a){var c={url:a.url,ns:a.uniqueKey,addon_key:a.addon_key,key:a.key,containerId:"embedded-"+a.uniqueKey,options:{history:{state:""},uniqueKey:a.uniqueKey,origin:a.origin,hostOrigin:a.hostOrigin,isFullPage:"1"===a.general,autoresize:!0,user:{timeZone:a.timeZone,fullName:a.fullName,uid:a.uid,ukey:a.ukey},productContext:h(a.productCtx),
structuredContext:h(a.structuredContext),contextJwt:a.contextJwt,contextPath:a.cp,width:a.w||a.width,height:a.h||a.height,targets:{env:{resize:"both"}}}};"string"===typeof a.contentClassifier&&(c.options.contentClassifier=a.contentClassifier);"number"===typeof a.hostFrameOffset&&(c.options.hostFrameOffset=a.hostFrameOffset+1);window._AP.isSubHost||(c.options.history.state=window.location.hash?window.location.hash.substr(2):"");return c};window._AP._createSub=function(a){var c=document.createElement("iframe"),
b=e().subCreate(a);b.width=a.options.width||"";b.height=a.options.height||"";b.style="border:0;";b["class"]="ap-iframe";b["data-addon-key"]=a.addon_key;b["data-key"]=a.key;delete b.src;Object.getOwnPropertyNames(b).forEach(function(a){c.setAttribute(a,b[a])});return c};window._AP.appendConnectAddon=function(a){var c=!1;try{window.top.karma&&(c=!0)}catch(d){}if(window===window.top||c)/com\.atlassian\.(jira|confluence)\.emcee($|\.local|\.staging|\.development\..*)/g.test(a.addon_key)?k("ac/marketplace",
function(b){b&&e().defineModule("marketplace",b);g(a)},20):g(a);else{var b=function(c){c.source===window.top&&c.data&&void 0!==c.data.hostFrameOffset&&(window.removeEventListener("message",b),a.hostFrameOffset=c.data.hostFrameOffset,g(a))};window.addEventListener("message",b);window.top.postMessage({type:"get_host_offset"},"*")}}})();
}catch(e){WRMCB(e)};