WRMCB=function(e){var c=console;if(c&&c.log&&c.error){c.log('Error running batched script.');c.error(e);}}
;
try {
/* module-key = 'com.atlassian.plugins.atlassian-connect-plugin:ap-extensions-v5', location = 'v5/js/core/connect-host-cookie.js' */
(function(p){"object"===typeof exports&&"undefined"!==typeof module?module.exports=p():"function"===typeof define&&define.amd?define([],p):("undefined"!==typeof window?window:"undefined"!==typeof global?global:"undefined"!==typeof self?self:this).connectHostCookie=p()})(function(){return function r(k,h,l){function m(b,e){if(!h[b]){if(!k[b]){var f="function"==typeof require&&require;if(!e&&f)return f(b,!0);if(n)return n(b,!0);e=Error("Cannot find module '"+b+"'");throw e.code="MODULE_NOT_FOUND",e;
}e=h[b]={exports:{}};k[b][0].call(e.exports,function(e){var a=k[b][1][e];return m(a?a:e)},e,e.exports,r,k,h,l)}return h[b].exports}for(var n="function"==typeof require&&require,f=0;f<l.length;f++)m(l[f]);return m}({1:[function(r,k,h){function l(a){a=new RegExp("\\b"+a.replace(q,"\\$\x26")+"\x3d((?:[^\\\\;]+|\\\\.)*)(?:;|$)");return(a=document.cookie.match(a))&&a[1].replace(b,"")}function m(a,d,c){var g=l("AJS.conglomerate.cookie"),b=new RegExp("(\\s|\\|)*\\b"+a.replace(q,"\\$\x26")+"\x3d[^|]*[|]*"),
g=(g||"").replace(b,"|");""!==d&&(a=a+"\x3d"+d,4020>g.length+a.length&&(g+="|"+a));g=g.replace(e,"|");c=c||365;a="";d='"'+g.replace(t,'\\"')+'"';c&&(a=new Date,a.setTime(+a+864E5*c),a="; expires\x3d"+a.toGMTString());document.cookie="AJS.conglomerate.cookie\x3d"+d+a+";path\x3d/"}function n(a,d){if(!a||0===a.length)throw Error("addon key must be defined on cookies");if(!d||0===d.length)throw Error("Name must be defined");return a+"$$"+d}function f(a){if(a&&a._context)return a._context.extension.addon_key;
throw Error("addon key not found in callback");}Object.defineProperty(h,"__esModule",{value:!0});var b=/(\\|^"|"$)/g,e=/\|\|+/g,t=/"/g,q=/[.*+?|^$()[\]{\\]/g;h["default"]={save:function(a,d,c){var g=arguments[arguments.length-1],b=n(f(g),a);g._context&&m(b,d,c)},read:function(a,d){d=arguments[arguments.length-1];var c;var b=n(f(d),a);c=(c=l("AJS.conglomerate.cookie"))||"";b=new RegExp(b.replace(q,"\\$\x26")+"\x3d([^|]+)");c=(c=c.match(b))&&c[1];c=null!=c?c:void 0;d(c);return c},erase:function(a){var b=
n(f(arguments[arguments.length-1]),a);m(b,"")}};k.exports=h["default"]},{}]},{},[1])(1)});
}catch(e){WRMCB(e)};
;
try {
/* module-key = 'com.atlassian.plugins.atlassian-connect-plugin:ap-extensions-v5', location = 'v5/js/core/connect-host-history.js' */
(function(C){"object"===typeof exports&&"undefined"!==typeof module?module.exports=C():"function"===typeof define&&define.amd?define([],C):("undefined"!==typeof window?window:"undefined"!==typeof global?global:"undefined"!==typeof self?self:this).connectHostHistory=C()})(function(){return function p(t,c,k){function g(f,b){if(!c[f]){if(!t[f]){var e="function"==typeof require&&require;if(!b&&e)return e(f,!0);if(m)return m(f,!0);b=Error("Cannot find module '"+f+"'");throw b.code="MODULE_NOT_FOUND",b;
}b=c[f]={exports:{}};t[f][0].call(b.exports,function(a){var b=t[f][1][a];return g(b?b:a)},b,b.exports,p,t,c,k)}return c[f].exports}for(var m="function"==typeof require&&require,q=0;q<k.length;q++)g(k[q]);return g}({1:[function(p,t,c){function k(a,r){(0,e.callConnectHost)(function(h){(0,e.values)(h.getExtensions()).forEach(function(e){e=e.extension.addon_key;var f=new b.Current({url:window.location.href,state:r.state}),f=new b.Route(f);h.broadcastEvent(a,{addon_key:e},f.render(e))})})}function g(){a||
(window.addEventListener("popstate",function(a){var b=(0,e.createEvent)("ap_popstate");b.state=(0,e.unwrapState)(a.state);window.dispatchEvent(b)}),window.addEventListener("ap_popstate",function(a){var b=(0,e.createEvent)("ap_changestate");b.state=a.state;window.dispatchEvent(b);k(f.HISTORY_POPSTATE,a)}),window.addEventListener("ap_pushstate",function(a){var b=(0,e.createEvent)("ap_changestate");b.state=a.state;window.dispatchEvent(b);k(f.HISTORY_PUSHSTATE,a)}),window.addEventListener("ap_replacestate",
function(a){var b=(0,e.createEvent)("ap_changestate");b.state=a.state;window.dispatchEvent(b);k(f.HISTORY_REPLACESTATE,a)}),window.addEventListener("ap_changestate",function(a){k(f.HISTORY_CHANGESTATE,a)}),a=!0)}function m(a){var b=a.state.render();a=a.url.render();window.history.pushState((0,e.wrapState)(b),a.title,a.url)}function q(a){var b=a.state.render();a=a.url.render();window.history.replaceState((0,e.wrapState)(b),a.title,a.url)}Object.defineProperty(c,"__esModule",{value:!0});var f=p("./constants"),
b=p("./models"),e=p("./utils"),a=!1;c["default"]={_registerWindowListeners:function(){g()},back:function(a){a=arguments[arguments.length-1];this.go(-1,a)},forward:function(a){a=arguments[arguments.length-1];this.go(1,a)},go:function(a){arguments[arguments.length-1]._context.extension.options.isFullPage?window.history.go(a):(0,e.log)("History is only available to page modules")},getState:function(a,f){f=arguments[arguments.length-1];var c=f._context.extension.addon_key,h=new b.Current({url:window.location.href,
state:(0,e.unwrapState)(window.history.state)}),c=(new b.Route(h)).render(c);a=a?"string"===typeof a?a:"hash":"hash";if("hash"===a)f(c.hash);else if("all"===a)f(c);else throw Error("invalid type for getState");},pushState:function(a,f){f=arguments[arguments.length-1];var c=f._context.extension.addon_key,h=new b.Current({url:window.location.href,state:(0,e.unwrapState)(window.history.state)}),h=new b.Route(h),c=new b.Change(a,c),c=new b.Route(c);f._context.extension.options.isFullPage?(c.url.isURLEqual(h.url)?
(h.merge(c),q(h)):c.url.isPathnameEqual(h.url)?(h.merge(c),m(h)):m(c),h=(0,e.createEvent)("ap_pushstate"),h.state=(0,e.unwrapState)(window.history.state),window.dispatchEvent(h)):(0,e.log)("History is only available to page modules")},replaceState:function(a,f){f=arguments[arguments.length-1];var c=f._context.extension.addon_key,h=new b.Current({url:window.location.href,state:(0,e.unwrapState)(window.history.state)}),h=new b.Route(h),c=new b.Change(a,c),c=new b.Route(c);f._context.extension.options.isFullPage?
(c.url.isURLEqual(h.url)?(h.merge(c),q(h)):c.url.isPathnameEqual(h.url)?(h.merge(c),q(h)):q(c),h=(0,e.createEvent)("ap_replacestate"),h.state=(0,e.unwrapState)(window.history.state),window.dispatchEvent(h)):(0,e.log)("History is only available to page modules")}};t.exports=c["default"]},{"./constants":7,"./models":8,"./utils":9}],2:[function(p,t,c){(function(k){(function(g){function m(a){throw RangeError(d[a]);}function q(a,d){for(var b=a.length;b--;)a[b]=d(a[b]);return a}function f(a,d){return q(a.split(w),
d).join(".")}function b(a){for(var d=[],b=0,l=a.length,e,c;b<l;)e=a.charCodeAt(b++),55296<=e&&56319>=e&&b<l?(c=a.charCodeAt(b++),56320==(c&64512)?d.push(((e&1023)<<10)+(c&1023)+65536):(d.push(e),b--)):d.push(e);return d}function e(a){return q(a,function(a){var d="";65535<a&&(a-=65536,d+=A(a>>>10&1023|55296),a=56320|a&1023);return d+=A(a)}).join("")}function a(a,d){return a+22+75*(26>a)-((0!=d)<<5)}function h(a,d,b){var l=0;a=b?z(a/700):a>>1;for(a+=z(a/d);455<a;l+=36)a=z(a/35);return z(l+36*a/(a+38))}
function r(a){var d=[],b=a.length,l,c=0,f=128,y=72,g,r,n,k,w;g=a.lastIndexOf("-");0>g&&(g=0);for(r=0;r<g;++r)128<=a.charCodeAt(r)&&m("not-basic"),d.push(a.charCodeAt(r));for(g=0<g?g+1:0;g<b;){r=c;l=1;for(n=36;;n+=36){g>=b&&m("invalid-input");k=a.charCodeAt(g++);k=10>k-48?k-22:26>k-65?k-65:26>k-97?k-97:36;(36<=k||k>z((2147483647-c)/l))&&m("overflow");c+=k*l;w=n<=y?1:n>=y+26?26:n-y;if(k<w)break;k=36-w;l>z(2147483647/k)&&m("overflow");l*=k}l=d.length+1;y=h(c-r,l,0==r);z(c/l)>2147483647-f&&m("overflow");
f+=z(c/l);c%=l;d.splice(c++,0,f)}return e(d)}function x(d){var l,e,c,f,g,k,r,y,n,w=[],u,x,q;d=b(d);u=d.length;l=128;e=0;g=72;for(k=0;k<u;++k)n=d[k],128>n&&w.push(A(n));for((c=f=w.length)&&w.push("-");c<u;){r=2147483647;for(k=0;k<u;++k)n=d[k],n>=l&&n<r&&(r=n);x=c+1;r-l>z((2147483647-e)/x)&&m("overflow");e+=(r-l)*x;l=r;for(k=0;k<u;++k)if(n=d[k],n<l&&2147483647<++e&&m("overflow"),n==l){y=e;for(r=36;;r+=36){n=r<=g?1:r>=g+26?26:r-g;if(y<n)break;q=y-n;y=36-n;w.push(A(a(n+q%y,0)));y=z(q/y)}w.push(A(a(y,
0)));g=h(e,x,c==f);e=0;++c}++e;++l}return w.join("")}var u="object"==typeof c&&c,p="object"==typeof t&&t&&t.exports==u&&t,v="object"==typeof k&&k;if(v.global===v||v.window===v)g=v;var B=/^xn--/,l=/[^ -~]/,w=/\x2E|\u3002|\uFF0E|\uFF61/g,d={overflow:"Overflow: input needs wider integers to process","not-basic":"Illegal input \x3e\x3d 0x80 (not a basic code point)","invalid-input":"Invalid input"},z=Math.floor,A=String.fromCharCode,n,v={version:"1.2.4",ucs2:{decode:b,encode:e},decode:r,encode:x,toASCII:function(a){return f(a,
function(a){return l.test(a)?"xn--"+x(a):a})},toUnicode:function(a){return f(a,function(a){return B.test(a)?r(a.slice(4).toLowerCase()):a})}};if(u&&!u.nodeType)if(p)p.exports=v;else for(n in v)v.hasOwnProperty(n)&&(u[n]=v[n]);else g.punycode=v})(this)}).call(this,"undefined"!==typeof global?global:"undefined"!==typeof self?self:"undefined"!==typeof window?window:{})},{}],3:[function(p,t,c){function k(){this.href=this.path=this.pathname=this.query=this.search=this.hash=this.hostname=this.port=this.host=
this.auth=this.slashes=this.protocol=null}function g(a,b,d){if(a&&m(a)&&a instanceof k)return a;var l=new k;l.parse(a,b,d);return l}function m(a){return"object"===typeof a&&null!==a}var q=p("punycode");c.parse=g;c.resolve=function(a,b){return g(a,!1,!0).resolve(b)};c.resolveObject=function(a,b){return a?g(a,!1,!0).resolveObject(b):b};c.format=function(a){"string"===typeof a&&(a=g(a));return a instanceof k?a.format():k.prototype.format.call(a)};c.Url=k;var f=/^([a-z0-9.+-]+:)/i,b=/:[0-9]*$/;t="{}|\\^`".split("").concat('\x3c\x3e"` \r\n\t'.split(""));
var e=["'"].concat(t),a=["%","/","?",";","#"].concat(e),h=["/","?","#"],r=/^[a-z0-9A-Z_-]{0,63}$/,x=/^([a-z0-9A-Z_-]{0,63})(.*)$/,u={javascript:!0,"javascript:":!0},D={javascript:!0,"javascript:":!0},v={http:!0,https:!0,ftp:!0,gopher:!0,file:!0,"http:":!0,"https:":!0,"ftp:":!0,"gopher:":!0,"file:":!0},B=p("querystring");k.prototype.parse=function(b,c,d){if("string"!==typeof b)throw new TypeError("Parameter 'url' must be a string, not "+typeof b);b=b.trim();var l=f.exec(b);if(l){var l=l[0],k=l.toLowerCase();
this.protocol=k;b=b.substr(l.length)}if(d||l||b.match(/^\/\/[^@\/]+@[^@\/]+/)){var n="//"===b.substr(0,2);!n||l&&D[l]||(b=b.substr(2),this.slashes=!0)}if(!D[l]&&(n||l&&!v[l])){n=-1;for(d=0;d<h.length;d++)l=b.indexOf(h[d]),-1!==l&&(-1===n||l<n)&&(n=l);n=-1===n?b.lastIndexOf("@"):b.lastIndexOf("@",n);-1!==n&&(d=b.slice(0,n),b=b.slice(n+1),this.auth=decodeURIComponent(d));n=-1;for(d=0;d<a.length;d++)l=b.indexOf(a[d]),-1!==l&&(-1===n||l<n)&&(n=l);-1===n&&(n=b.length);this.host=b.slice(0,n);b=b.slice(n);
this.parseHost();this.hostname=this.hostname||"";n="["===this.hostname[0]&&"]"===this.hostname[this.hostname.length-1];if(!n){var g=this.hostname.split(/\./);d=0;for(l=g.length;d<l;d++){var m=g[d];if(m&&!m.match(r)){for(var w="",p=0,t=m.length;p<t;p++)w=127<m.charCodeAt(p)?w+"x":w+m[p];if(!w.match(r)){l=g.slice(0,d);d=g.slice(d+1);if(m=m.match(x))l.push(m[1]),d.unshift(m[2]);d.length&&(b="/"+d.join(".")+b);this.hostname=l.join(".");break}}}}this.hostname=255<this.hostname.length?"":this.hostname.toLowerCase();
if(!n){m=this.hostname.split(".");g=[];for(d=0;d<m.length;++d)l=m[d],g.push(l.match(/[^A-Za-z0-9_-]/)?"xn--"+q.encode(l):l);this.hostname=g.join(".")}d=this.port?":"+this.port:"";this.host=(this.hostname||"")+d;this.href+=this.host;n&&(this.hostname=this.hostname.substr(1,this.hostname.length-2),"/"!==b[0]&&(b="/"+b))}if(!u[k])for(d=0,l=e.length;d<l;d++)n=e[d],m=encodeURIComponent(n),m===n&&(m=escape(n)),b=b.split(n).join(m);d=b.indexOf("#");-1!==d&&(this.hash=b.substr(d),b=b.slice(0,d));d=b.indexOf("?");
-1!==d?(this.search=b.substr(d),this.query=b.substr(d+1),c&&(this.query=B.parse(this.query)),b=b.slice(0,d)):c&&(this.search="",this.query={});b&&(this.pathname=b);v[k]&&this.hostname&&!this.pathname&&(this.pathname="/");if(this.pathname||this.search)d=this.pathname||"",l=this.search||"",this.path=d+l;this.href=this.format();return this};k.prototype.format=function(){var a=this.auth||"";a&&(a=encodeURIComponent(a),a=a.replace(/%3A/i,":"),a+="@");var b=this.protocol||"",d=this.pathname||"",e=this.hash||
"",c=!1,f="";this.host?c=a+this.host:this.hostname&&(c=a+(-1===this.hostname.indexOf(":")?this.hostname:"["+this.hostname+"]"),this.port&&(c+=":"+this.port));this.query&&m(this.query)&&Object.keys(this.query).length&&(f=B.stringify(this.query));a=this.search||f&&"?"+f||"";b&&":"!==b.substr(-1)&&(b+=":");this.slashes||(!b||v[b])&&!1!==c?(c="//"+(c||""),d&&"/"!==d.charAt(0)&&(d="/"+d)):c||(c="");e&&"#"!==e.charAt(0)&&(e="#"+e);a&&"?"!==a.charAt(0)&&(a="?"+a);d=d.replace(/[?#]/g,function(a){return encodeURIComponent(a)});
a=a.replace("#","%23");return b+c+d+a+e};k.prototype.resolve=function(a){return this.resolveObject(g(a,!1,!0)).format()};k.prototype.resolveObject=function(a){if("string"===typeof a){var b=new k;b.parse(a,!1,!0);a=b}var d=new k;Object.keys(this).forEach(function(a){d[a]=this[a]},this);d.hash=a.hash;if(""===a.href)return d.href=d.format(),d;if(a.slashes&&!a.protocol)return Object.keys(a).forEach(function(b){"protocol"!==b&&(d[b]=a[b])}),v[d.protocol]&&d.hostname&&!d.pathname&&(d.path=d.pathname="/"),
d.href=d.format(),d;if(a.protocol&&a.protocol!==d.protocol){if(!v[a.protocol])return Object.keys(a).forEach(function(b){d[b]=a[b]}),d.href=d.format(),d;d.protocol=a.protocol;if(a.host||D[a.protocol])d.pathname=a.pathname;else{for(var e=(a.pathname||"").split("/");e.length&&!(a.host=e.shift()););a.host||(a.host="");a.hostname||(a.hostname="");""!==e[0]&&e.unshift("");2>e.length&&e.unshift("");d.pathname=e.join("/")}d.search=a.search;d.query=a.query;d.host=a.host||"";d.auth=a.auth;d.hostname=a.hostname||
a.host;d.port=a.port;if(d.pathname||d.search)d.path=(d.pathname||"")+(d.search||"");d.slashes=d.slashes||a.slashes;d.href=d.format();return d}var b=d.pathname&&"/"===d.pathname.charAt(0),c=a.host||a.pathname&&"/"===a.pathname.charAt(0),f=b=c||b||d.host&&a.pathname,h=d.pathname&&d.pathname.split("/")||[],e=a.pathname&&a.pathname.split("/")||[],g=d.protocol&&!v[d.protocol];g&&(d.hostname="",d.port=null,d.host&&(""===h[0]?h[0]=d.host:h.unshift(d.host)),d.host="",a.protocol&&(a.hostname=null,a.port=null,
a.host&&(""===e[0]?e[0]=a.host:e.unshift(a.host)),a.host=null),b=b&&(""===e[0]||""===h[0]));if(c)d.host=a.host||""===a.host?a.host:d.host,d.hostname=a.hostname||""===a.hostname?a.hostname:d.hostname,d.search=a.search,d.query=a.query,h=e;else if(e.length)h||(h=[]),h.pop(),h=h.concat(e),d.search=a.search,d.query=a.query;else if(null!=a.search){g&&(d.hostname=d.host=h.shift(),g=d.host&&0<d.host.indexOf("@")?d.host.split("@"):!1)&&(d.auth=g.shift(),d.host=d.hostname=g.shift());d.search=a.search;d.query=
a.query;if(null!==d.pathname||null!==d.search)d.path=(d.pathname?d.pathname:"")+(d.search?d.search:"");d.href=d.format();return d}if(!h.length)return d.pathname=null,d.path=d.search?"/"+d.search:null,d.href=d.format(),d;for(var c=h.slice(-1)[0],e=(d.host||a.host)&&("."===c||".."===c)||""===c,l=0,r=h.length;0<=r;r--)c=h[r],"."==c?h.splice(r,1):".."===c?(h.splice(r,1),l++):l&&(h.splice(r,1),l--);if(!b&&!f)for(;l--;l)h.unshift("..");!b||""===h[0]||h[0]&&"/"===h[0].charAt(0)||h.unshift("");e&&"/"!==h.join("/").substr(-1)&&
h.push("");f=""===h[0]||h[0]&&"/"===h[0].charAt(0);g&&(d.hostname=d.host=f?"":h.length?h.shift():"",g=d.host&&0<d.host.indexOf("@")?d.host.split("@"):!1)&&(d.auth=g.shift(),d.host=d.hostname=g.shift());(b=b||d.host&&h.length)&&!f&&h.unshift("");h.length?d.pathname=h.join("/"):(d.pathname=null,d.path=null);if(null!==d.pathname||null!==d.search)d.path=(d.pathname?d.pathname:"")+(d.search?d.search:"");d.auth=a.auth||d.auth;d.slashes=d.slashes||a.slashes;d.href=d.format();return d};k.prototype.parseHost=
function(){var a=this.host,e=b.exec(a);e&&(e=e[0],":"!==e&&(this.port=e.substr(1)),a=a.substr(0,a.length-e.length));a&&(this.hostname=a)}},{punycode:2,querystring:6}],4:[function(p,t,c){t.exports=function(c,m,q,f){q=q||"\x3d";var b={};if("string"!==typeof c||0===c.length)return b;var e=/\+/g;c=c.split(m||"\x26");m=1E3;f&&"number"===typeof f.maxKeys&&(m=f.maxKeys);f=c.length;0<m&&f>m&&(f=m);for(m=0;m<f;++m){var a=c[m].replace(e,"%20"),h=a.indexOf(q),g;0<=h?(g=a.substr(0,h),a=a.substr(h+1)):(g=a,a=
"");g=decodeURIComponent(g);a=decodeURIComponent(a);Object.prototype.hasOwnProperty.call(b,g)?k(b[g])?b[g].push(a):b[g]=[b[g],a]:b[g]=a}return b};var k=Array.isArray||function(c){return"[object Array]"===Object.prototype.toString.call(c)}},{}],5:[function(p,t,c){function k(c,b){if(c.map)return c.map(b);for(var e=[],a=0;a<c.length;a++)e.push(b(c[a],a));return e}var g=function(c){switch(typeof c){case "string":return c;case "boolean":return c?"true":"false";case "number":return isFinite(c)?c:"";default:return""}};
t.exports=function(c,b,e,a){b=b||"\x26";e=e||"\x3d";null===c&&(c=void 0);return"object"===typeof c?k(q(c),function(a){var h=encodeURIComponent(g(a))+e;return m(c[a])?k(c[a],function(a){return h+encodeURIComponent(g(a))}).join(b):h+encodeURIComponent(g(c[a]))}).join(b):a?encodeURIComponent(g(a))+e+encodeURIComponent(g(c)):""};var m=Array.isArray||function(c){return"[object Array]"===Object.prototype.toString.call(c)},q=Object.keys||function(c){var b=[],e;for(e in c)Object.prototype.hasOwnProperty.call(c,
e)&&b.push(e);return b}},{}],6:[function(p,t,c){c.decode=c.parse=p("./decode");c.encode=c.stringify=p("./encode")},{"./decode":4,"./encode":5}],7:[function(p,t,c){Object.defineProperty(c,"__esModule",{value:!0});c.STATE_AP_KEY="_AP";c.QUERY_KEY_PREFIX="ac";c.QUERY_KEY_DELIMITER=".";c.ANCHOR_PREFIX="!";c.HISTORY_POPSTATE="history_popstate";c.HISTORY_PUSHSTATE="history_pushstate";c.HISTORY_REPLACESTATE="history_replacestate";c.HISTORY_CHANGESTATE="history_changestate"},{}],8:[function(p,t,c){function k(a){a=
a||{};if(!a.key)throw Error("missing key for addon");this.key=a.key;this.state=a.state;this.query=a.query||{};return this}function g(a){a=a||{};a.models=a.models||[];a.models instanceof Array||(a.models=[a.models]);a.models=a.models.map(function(a){return a instanceof k?a:new k(a)});this.models=a.models;return this}function m(a){a=a||{};a.addons=a.addons||[];a.addons instanceof g||(a.addons=new g(a.addons));this.addons=a.addons;return this}function q(a){a=a||{};a.addons=a.addons||[];a.global=a.global||
[];a.parsed instanceof b["default"].Url||(a.parsed=b["default"].parse(a.url));a.addons instanceof g||(a.addons=new g(a.addons));this.parsed=a.parsed;this.addons=a.addons;this.global=a.global;this.title=a.title||window.document.title}function f(a){a=a||{};if(!a.url)throw Error("missing url option");a.url instanceof q||(a.url=new q(a.url));if(!a.state)throw Error("missing state option");a.state instanceof m||(a.state=new m(a.state));this.url=a.url;this.state=a.state}Object.defineProperty(c,"__esModule",
{value:!0});c.Addon=k;c.Addons=g;c.Current=function(a){a=a||{};if(!a.url)throw Error("missing url");var c=b["default"].parse(a.url),f=new g,c=(0,e.parseQuery)(c.query).map(e.stripAddonQueryPrefix),x=(0,e.normalizeQueryByAddons)(c),c=x.filter(function(a){return a.key}),x=x.filter(function(a){return!a.key});c.forEach(function(a){a=new k(a);f.add(a)});this.url=new q({url:a.url,addons:f,global:x});this.state=new m(a.state);return this};c.Change=function(a,c){var h=typeof a,f=b["default"].parse(window.location.href),
u={},p,t;if("string"===h)u.protocol=f.protocol,u.slashes=f.slashes,u.hostname=f.hostname,u.pathname=f.pathname,u.port=f.port,u.search=f.search,u.query=f.query,u.hash=(0,e.addHash)((0,e.addHashPrefix)(a));else if("object"===h)t=a.href?b["default"].parse(a.href):f,u.protocol=f.protocol,u.slashes=f.slashes,u.hostname=f.hostname,u.port=f.port,u.pathname=t.pathname||f.pathname,u.search=null,u.query=null,u.hash=a.hash?(0,e.addHash)((0,e.addHashPrefix)(a.hash)):null,p=a.state,t=a.query;else throw Error("invalid option type");
f=new g;a=new g;p&&(p=new k({key:c,state:p}),f.add(p));t&&(c=new k({key:c,query:t}),a.add(c));c=new m({addons:f});u=new q({url:b["default"].format(u),addons:a});this.state=c;this.url=u;return this};c.State=m;c.URL=q;c.Route=f;var b=(t=p("url"))&&t.__esModule?t:{"default":t},e=p("./utils");g.prototype.add=function(a){this.models.push(a)};g.prototype.remove=function(a){this.models.splice(this.models.indexOf(a),1)};g.prototype.find=function(a){return(0,e.find)(this.models,function(b){return b.key===
a})};g.prototype.merge=function(a){var b=this.find(a.key);b&&this.remove(b);this.add(a)};m.prototype.merge=function(a){var b=this;a.addons.models.forEach(function(a){b.addons.merge(a)})};m.prototype.render=function(){return(0,e.deepCopy)(this)};q.prototype.isURLEqual=function(a){return this.render().url===a.render().url};q.prototype.isPathnameEqual=function(a){var b=this.parsed.slashes===a.parsed.slashes,c=this.parsed.hostname===a.parsed.hostname,e=this.parsed.pathname===a.parsed.pathname;return this.parsed.protocol===
a.parsed.protocol&&b&&c&&e};q.prototype.merge=function(a){var b=this;b.parsed.hash=a.parsed.hash;a.addons.models.forEach(function(a){b.addons.merge(a)})};q.prototype.render=function(){var a=(0,e.deepCopy)(this),c=a.parsed,f=(0,e.denormalizeQueryByAddons)(this.addons.models),g=(0,e.denormalizeQueryByAddons)(this.global),f=f.concat(g).map(e.addAddonQueryPrefix),f=(0,e.formatQuery)(f);c.query=f;c.search=c.query?"?"+c.query:null;a.url=b["default"].format(c);return a};f.prototype.merge=function(a){this.url.merge(a.url);
this.state.merge(a.state)};f.prototype.render=function(a){return(0,e.deepCopy)({key:a,hash:(0,e.stripHashPrefix)((0,e.stripHash)(this.url.parsed.hash)),query:this.url.addons.find(a)?this.url.addons.find(a).query:null,title:this.url.title,href:this.url.parsed.href,state:this.state.addons.find(a)?this.state.addons.find(a).state:null})}},{"./utils":9,url:3}],9:[function(p,t,c){function k(b,c,a){c in b?Object.defineProperty(b,c,{value:a,enumerable:!0,configurable:!0,writable:!0}):b[c]=a;return b}function g(b){return void 0===
b||null===b||""===b?"":b.toString().replace(new RegExp("^"+f.ANCHOR_PREFIX),"")}function m(b){b=b?b.split("\x3d"):[];return 2===b.length?{key:b[0],value:b[1]}:null}function q(b){return"key"in b&&"value"in b?[b.key,"\x3d",b.value].join(""):null}Object.defineProperty(c,"__esModule",{value:!0});c.find=function(b,c){for(var a=0,e=b.length;a<e;a+=1)if(c(b[a]))return b[a]};c.values=function(b){var c=[];if(!b)return c;for(var a in b)c.push(b[a]);return c};c.stripHash=function(b){return b?b.slice(b.search("#")+
1):null};c.stripHashPrefix=g;c.addHash=function(b){return"#"+b};c.addHashPrefix=function(b){if(void 0===b||null===b)throw"You must supply text to prefix";return f.ANCHOR_PREFIX+g(b)};c.splitQueryParam=m;c.joinQueryParam=q;c.parseQuery=function(b){return(b?b.split("\x26"):[]).map(function(b){return m(b)}).filter(function(b){return b})};c.formatQuery=function(b){b=b.map(function(b){return q(b)}).filter(function(b){return b});return b.length?b.join("\x26"):null};c.stripAddonQueryPrefix=function(b){var c=
b.key?b.key.split(f.QUERY_KEY_DELIMITER):[],a=f.QUERY_KEY_PREFIX;return 3<=c.length&&a===c[0]?(a=c.slice(1,c.length-1).join(f.QUERY_KEY_DELIMITER),c=c.slice(c.length-1).join(f.QUERY_KEY_DELIMITER),{addonKey:a,key:c,value:b.value}):b};c.addAddonQueryPrefix=function(b){var c=f.QUERY_KEY_PREFIX;return"addonKey"in b&&b.addonKey?{key:[c,b.addonKey,b.key].join(f.QUERY_KEY_DELIMITER),value:b.value}:b};c.normalizeQueryByAddons=function(b){var c=[];b.forEach(function(a){var b=a.key,e=a.value,f=a.addonKey;
(a=c.filter(function(a){return a.key===f}))&&a.length?a[0].query[b]=e:c.push({key:f,query:k({},b,e)})});return c};c.denormalizeQueryByAddons=function(b){var c=[];b.forEach(function(a){var b=a.key;Object.keys(a.query).forEach(function(e){c.push({addonKey:b,key:e,value:a.query[e]})})});return c};c.deepCopy=function(b){return JSON.parse(JSON.stringify(b))};c.wrapState=function(b){var c={};c[f.STATE_AP_KEY]=b;return c};c.unwrapState=function(b){return b&&b[f.STATE_AP_KEY]?b[f.STATE_AP_KEY]:null};c.createEvent=
function(b){if("function"===typeof Event)var c=new Event(b);else c=document.createEvent("Event"),c.initEvent(b,!1,!1);return c};c.callConnectHost=function(b){p&&p.amd?p(["connect-host"],function(c){b(c)}):b(window.connectHost)};c.log=function(b,c){c||(c="log");console[c].call(null,"Atlassian Connect JS History: ",b)};var f=p("./constants")},{"./constants":7}]},{},[1])(1)});
}catch(e){WRMCB(e)};
;
try {
/* module-key = 'com.atlassian.plugins.atlassian-connect-plugin:ap-extensions-v5', location = 'v5/js/core/connect-host-request.js' */
(function(t){"object"===typeof exports&&"undefined"!==typeof module?module.exports=t():"function"===typeof define&&define.amd?define([],t):("undefined"!==typeof window?window:"undefined"!==typeof global?global:"undefined"!==typeof self?self:this).connectHostRequest=t()})(function(){return function v(n,d,p){function m(k,h){if(!d[k]){if(!n[k]){var l="function"==typeof require&&require;if(!h&&l)return l(k,!0);if(q)return q(k,!0);h=Error("Cannot find module '"+k+"'");throw h.code="MODULE_NOT_FOUND",h;
}h=d[k]={exports:{}};n[k][0].call(h.exports,function(d){var h=n[k][1][d];return m(h?h:d)},h,h.exports,v,n,d,p)}return d[k].exports}for(var q="function"==typeof require&&require,l=0;l<p.length;l++)m(p[l]);return m}({1:[function(v,n,d){function p(){if(window.AJS&&window.AJS.contextPath)return window.AJS.contextPath();var a=document.querySelector("meta[name\x3dajs-context-path]");return a?a.getAttribute("content"):""}function m(a){return a.replace(/(http[s]?:\/\/[^"]*?&jwt=[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*.*?)\\"/gi,
'\\"')}function q(a){var e={headers:{}};h.forEach(function(c,g){e[c]=a[c];if("responseText"===c)try{JSON.parse(a[c]),e[c]=m(a[c])}catch(y){}},this);w.forEach(function(c,g){e.headers[c]=a.getResponseHeader(c)},this);return e}function l(a,e,c){c._isBlob&&c.blob&&c.name?a.append(e,c.blob,c.name):a.append(e,c);return a}function k(a){a.contentType=!1;a.processData=!1;if(a.data&&"object"===typeof a.data){var e=new FormData;Object.keys(a.data).forEach(function(c){var g=a.data[c];Array.isArray(g)?g.forEach(function(a,
b){e=l(e,c+"["+b+"]",a)}):e=l(e,c,g)});a.data=e;a.headers["X-Atlassian-Token"]="no-check"}else throw Error("For a Multipart request, data must to be an Object");return a}Object.defineProperty(d,"__esModule",{value:!0});var h=["status","statusText","responseText"],w=["Content-Type","ETag"],x=["If-Match","If-None-Match","X-Atlassian-Force-Account-ID"],r;d.stripJWTUrls=m;d.addRequestMarshal=function(a){if("function"===typeof a)r=a;else throw Error("ACJS request marshal must be a function");};d.removeRequestMarshal=
function(){r=void 0};d["default"]={request:function(a,e){function c(a,b,c){e(c,q(a),c)}var g=p(),d={};e=arguments[arguments.length-1];"string"===typeof a&&(a={url:a});g+=a.url;g=g.replace(/\/\.\.\//ig,"");a.headers=a.headers||{};Object.getOwnPropertyNames(a.headers).forEach(function(b){d[b.toLowerCase()]=a.headers[b]},this);var b={url:g,type:a.type||"GET",data:a.data,dataType:"text",contentType:a.contentType,cache:"undefined"!==typeof a.cache?!!a.cache:void 0,headers:{Accept:d.accept||"*/*","AP-Client-Key":e._context.extension.addon_key}};
"multipart/form-data"===b.contentType&&(b=k(b));b.data&&"object"===typeof b.data&&"GET"===b.type.toUpperCase()&&Object.keys(b.data).forEach(function(a){b.url+=(0<=b.url.indexOf("?")?"\x26":"?")+encodeURIComponent(a)+"\x3d"+encodeURIComponent(b.data[a])});!0===a.experimental&&(b.headers["X-ExperimentalApi"]="opt-in");x.forEach(function(a,c){d[a.toLowerCase()]&&(b.headers[a]=d[a.toLowerCase()])},this);b.cache||(b.url+=(0<=b.url.indexOf("?")?"\x26":"?")+"_r\x3d"+(new Date).getTime());var f=new XMLHttpRequest;
f.open(b.type,b.url,!0);b.contentType&&(b.headers["Content-type"]=b.contentType);Object.getOwnPropertyNames(b.headers).forEach(function(a){f.setRequestHeader(a,b.headers[a])});f.onload=function(){if(200<=this.status&&300>this.status){var a=f.responseText;e(!1,q(f),a)}else c(f,f.statusText,f.responseText)};f.onerror=function(){c(f,f.statusText,f.responseText)};try{g=!0,r&&(g=r.call(null,b)),!0===g?f.send(b.data||null):(f.abort(),c(f,"string"===typeof g?g:void 0,g))}catch(u){f.abort(),c(f,void 0,u),
console.error("ACJS Request: ",u.message,u)}}}},{}]},{},[1])(1)});
}catch(e){WRMCB(e)};